services:

  airflow-init:
    image: apache/airflow:2.10.5

    container_name: airflow_init_ml

    env_file:
      - .env

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres:5432/${AIRFLOW_DB_NAME}

    volumes:
      - ./init_airflow.sh:/opt/airflow/init_airflow.sh

    command: >
      bash /opt/airflow/init_airflow.sh
   
  airflow-webserver:
    image: apache/airflow:2.10.5

    container_name: airflow_webserver_ml

    env_file:
      - .env

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__WEBSERVER__WORKERS: 1

    depends_on:
      - airflow-init

    ports:
      - "8081:8080"

    volumes:
      - ./Production/dags:/opt/airflow/dags
      - ./Production/logs:/opt/airflow/logs
      - ./.env:/opt/airflow/.env
      - ./neondb_credentials.env:/opt/airflow/neondb_credentials.env
      - ./ml_forecasting_db.env:/opt/airflow/ml_forecasting_db.env
      - ./init_airflow.sh:/opt/airflow/init_airflow.sh

    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.10.5

    container_name: airflow_scheduler_ml

    env_file:
      - .env

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres:5432/${AIRFLOW_DB_NAME}

    depends_on:
      - airflow-init

    volumes:
      - ./Production/dags:/opt/airflow/dags
      - ./Production/logs:/opt/airflow/logs
      - ./.env:/opt/airflow/.env
      - ./neondb_credentials.env:/opt/airflow/neondb_credentials.env
      - ./ml_forecasting_db.env:/opt/airflow/ml_forecasting_db.env
      - ./init_airflow.sh:/opt/airflow/init_airflow.sh

    command: scheduler

networks:
  default:
    external: true
    name: data_engineering_lab_default
